[#ftl]
[@b.grid items=applyList var="apply" sortable="true"]
[@b.gridbar]
  bar.addItem("导出",action.exportData("lesson.no:课程序号,lesson.course.name:课程名称,lesson.course.code:课程代码,lesson.courseType.name:课程类别,lesson.campus.name:校区,lesson.course.credits:学分,lesson.teachDepart.name:开课院系,semester.code:学年学期,lesson.teachClass.name:教学班名称,lesson.teachClass.depart.name:上课院系,lesson.teachClass.grade:入学年份,lesson.langType.name:授课语言,borrower.name:申请教师,tel:联系电话,software:所需软件,mediaRoom:上课地点"))
  [/@]
	[@b.row]
		[@b.col width="4%" title="序号"]${apply_index+1}[/@]
		[@b.col width="5%" property="lesson.no" title="attr.taskNo"]${apply.lesson.no?if_exists}[/@]
		[@b.col width="10%" property="lesson.course.name" title="attr.courseName"]${apply.lesson.course.name?if_exists}[/@]
		[@b.col width="11%" property="lesson.courseType.name" title="entity.courseType"]${apply.lesson.courseType.name?if_exists}[/@]
		[@b.col width="17%" property="lesson.teachClass.name" title="entity.teachClass"]${apply.lesson.teachClass.name?if_exists}[/@]
		[@b.col width="7%" property="borrower.name" title="申请教师"]${apply.borrower.name?if_exists}[/@]
		[@b.col width="15%"  title="上课地点"]${rooms.get(apply)!}[/@]
		[@b.col width="15%" property="software" title="使用软件"/]
    [@b.col width="11%" title="多媒体软件需求"][@b.a href="!info?apply.id=${apply.id}"]查看[/@][/@]
	[/@]
[/@]