[#ftl]
[@b.head/]
[@b.grid items=lessons var="l" sortable="true"]
[@b.gridbar/]
    [@b.row]
      [@b.boxcol width="3%"/]
      [@b.col width="5%" property="no" title="课程序号"/]
      [@b.col width="7%" property="course.code" title="课程代码" /]
      [@b.col width="20%" property="course.name" title="attr.courseName"/]
      [@b.col width="10%" property="courseType.name" title="entity.courseType" /]
      [@b.col width="7%" property="campus.name" title="校区"/]
      [@b.col width="20%" property="teachClass.name" title="entity.teachClass"]${l.teachClass.name?if_exists}[/@]
      [@b.col width="8%" property="teacher.user.name" title="entity.teacher" sortable="false"]
        [#list l.teachers as teacher]
          ${teacher.user.name}[#if teacher_has_next],[/#if]
        [/#list]
      [/@]
      [@b.col width="5%" property="teachClass.stdCount" title="上课人数"/]
      [@b.col width="15%" title="排课安排" filterable="false"]${arrangeInfo[l.id?string]}[/@]
    [/@]
[/@]
[@b.foot/]