[#ftl]
[@b.head/]
[@b.form name="lessonSearchForm" action="!search" target="contentDiv"]
[@b.grid items=lessons var="lesson" sortable="true"]
  [@b.gridbar title="课程实验规划"/]
  [@b.row]
        [@b.boxcol /]
        [@b.col width="10%" property="no" title="课程序号"/]
        [@b.col width="10%" property="course.name" title="课程名称" /]
        [@b.col width="10%" property="teachDepart.name" title="开课院系" /]
        [@b.col width="10%" property="courseType.name" title="课程类别" /]
        [@b.col width="10%" property="name" title="上课地点" /]
        [@b.col width="10%" property="schedule.weektime" title="课程安排" /]
        [@b.col title="操作" width="30%"]
            [@b.a href="!addLab?lesson.id=${lesson.id}"]添加/修改多媒体教室软件需求[/@]
        [/@]
[/@]
[/@]
[/@]
[@b.foot/]