[#ftl]
[@b.head/]
[@b.toolbar title="添加/修改课外实验计划"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if lab.id?? && lab.id!=0]!update?id=${lab.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list" name="actionForm"]
    [@b.select  name="lab.semester.id" label="学年学期" items=semesters?sort_by("code") value=currentSemester option = "id,code" empty="..."/]
    [@b.textfield name="lab.name" label="实验课程名称" value="${lab.name!}" required="true" maxlength="20"/]
    [@b.textfield name="lab.tel" label="联系电话" value="${lab.tel!}" required="true" maxlength="20"/]
    [@b.textfield name="lab.audience" label="听课对象" value="${lab.audience!}" required="true" maxlength="20"/]
    [@b.textfield name="lab.stdCount" label="上机人数" value="${lab.stdCount!}" required="true" maxlength="20"/]
    [@b.textfield name="lab.itemCount" label=">实验项目数(只限数字)" value="${(lab.itemCount)!}" required="true" maxlength="20"/]
    [#list 1..5 as i]
    [@b.textarea label="实验项目" check="maxLength(200)" name="item.content"  style="width:500px" maxlength="100" /]
    [/#list]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]

